### ISSUE TITLE
Will the plugin work for me?

### ISSUE THREAD

**Issue by Cutecat42** [LevelMaster/LevelMaster#1]
I want to have several clans, where people can earn levels from killing others in different clans, and they would lose levels when others killed them. To kill others, they would use magic spells...when they're, say, Level one, they have access to one spell, and when they level up they have access to other spells (and when they die, they lose access again). Would this plugin be able to do that? Also, I want each clan to have reputation (or like power in factions). It would be different from players skills, but you get and lose it the same way (reputation is basically the whole clans levels combined). Would this plugin work for that as well?

**Comment by zrocweb** [comment]
Hey!  I like your ideas and will incorporate them into the plugin.  For the most part the way it is now, your ways will work but I do have to make a few changes to the beta (before release) to get it exactly like you described.   

Will work on it.. But am still traveling so can't really do much on the development until I return home.
